language: c

dist: trusty
sudo: required
services:
- docker

env:
  matrix:
  - JOB_ARCH=amd64
  - JOB_ARCH=arm64
  - JOB_ARCH=armel
  - JOB_ARCH=armhf
  - JOB_ARCH=i386
  - JOB_ARCH=mips
  - JOB_ARCH=mips64el
  - JOB_ARCH=mipsel
  - JOB_ARCH=ppc64el
  - JOB_ARCH=s390x
  global:
  - DOCKER_EXEC_ROOT="sudo docker exec --interactive --tty --user root test_container"
  - DOCKER_EXEC="sudo docker exec --interactive --tty test_container"
  - DOCKER_EXEC_NOTTY="sudo docker exec test_container"
  - BINTRAY_USER=laarid
  - BINTRAY_REPO=main
  - BINTRAY_COMPONENT=main
  - BINTRAY_DESC="The Mesa 3D Graphics Library"

branches:
  only:
  - master
  - release

addons:
  apt:
    sources:
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu/ devel universe'
    packages:
    - binfmt-support
    - qemu-user-static

cache:
- apt
- ccache

before_install:
- test -d "${HOME}/.ccache/${JOB_ARCH}" || mkdir -p "${HOME}/.ccache/${JOB_ARCH}"
- |
  sudo docker run --detach --interactive --tty \
    --name test_container \
    --volume ${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}}:${TRAVIS_BUILD_DIR%${TRAVIS_REPO_SLUG}} \
    --volume ${HOME}/.ccache/${JOB_ARCH}:/home/laarid/.ccache \
    --workdir ${TRAVIS_BUILD_DIR} \
    --env 'PATH=/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
    --add-host dl.bintray.com:$(nslookup dl.bintray.com | grep -m1 -A1 Name: | grep Address: | awk '{print $2}') \
    laarid/devel:${JOB_ARCH} \
    /bin/bash

install:
- ${DOCKER_EXEC_ROOT} apt-get update -qq
- |
  ${DOCKER_EXEC} \
    mk-build-deps --install --remove \
      --host-arch ${JOB_ARCH} \
      --root-cmd sudo \
      --tool 'apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y --allow-unauthenticated'

script:
- ${DOCKER_EXEC} ccache --zero-stats
- ${DOCKER_EXEC} dpkg-buildpackage --host-arch ${JOB_ARCH} -i -us -uc -b
- |
  if ! ${DOCKER_EXEC} make -C build -j $(nproc) -k check; then
    case "${JOB_ARCH}" in
      amd64|armel|i386|s390x)
        exit 1;
        ;;
      *)
        echo "WARNING: 'make check' failure on this platform is expected. Quit.";
        ;;
    esac
  fi
- ${DOCKER_EXEC} ccache --show-stats

before_deploy:
- |
  cat debian/bintray.json.in | \
    sed -e "s#@BINTRAY_PACKAGE@#$(cat debian/control | grep ^Source: | awk '{print $2}')#g" \
        -e "s#@BINTRAY_USER@#${BINTRAY_USER}#g" \
        -e "s#@BINTRAY_REPO@#${BINTRAY_REPO}#g" \
        -e "s#@BINTRAY_DESC@#${BINTRAY_DESC}#g" \
        -e "s#@GITHUB_REPO@#${TRAVIS_REPO_SLUG}#g" \
        -e "s,@BINTRAY_VERSION@,$(cat debian/changelog | head -n 1 | sed 's,.*(\(.*\)).*,\1,'),g" \
        -e "s#@BINTRAY_RELEASE_DATE@#$(cat debian/changelog | grep -m 1 '^ -- ' | sed 's,^.*  ,,')#g" \
        -e "s#@BINTRAY_OUTDIR@#$(dirname ${TRAVIS_BUILD_DIR})#g" \
        -e "s#@BINTRAY_POOLABBR@#$(cat debian/control | grep ^Source: | awk '{print $2}' | cut -c1)#g" \
        -e "s#@BINTRAY_SUITE@#$(${DOCKER_EXEC_NOTTY} cat /etc/apt/sources.list | grep -m 1 '^deb ' | awk '{print $3}')#g" \
        -e "s#@BINTRAY_COMPONENT@#${BINTRAY_COMPONENT}#g" \
        -e "s#@BINTRAY_ARCH@#${JOB_ARCH}#g" | \
    tee debian/bintray.json

deploy:
- provider: bintray
  file: debian/bintray.json
  user: vicamo
  key:
    secure: "tXfmyvKmYAoZW3DF9Gj+tQuuhujUatDkLty0uimGcO0QMgEcCE7xy495nJjxnYd4BYnB+9Ykfu1SuvWNZmyrRrEuFq4wj82mw+HH6rSbWl8xuV2BdT4CYPV85NN5NSfR5Fq3NHzxPmwqzFZXSrwKLQlAd1sGaWiXBIMwVFZmumvLnyttRwInCcXY7njjK223RpgB70SenFkRzK5/ofaAyiFCr7S8D/olP7vRtwoT5Ab4h0fJmcoSdchjhWCZ2rZhykmxaW7VK322Qr2ZU+UzMGqV8k8h/LyX46RD74Ux4LpW0v5nl8gCEvAd2QeBabvfZH5okSKeYPBU7aHoxydmC90jWJn8CRvhTS7nZPazlGv1AvsIb2mCgnx2qaYUgOvmnDXaONN+gYcNdHWwocLXEy4EuX30nxEGZoDbJX4Ra5h78QeZSnN5ekRyGe5Q8Xz7W/a2eDM2Q2cMadv/xq+OhmalfXWOP2DjquLGyKHk4itCbPrH6B7okvtoh1WLZg25PmABe4QN9+RL6AAqbfxCp2Iv891hz6uXnpX1vgb9viinQjW9+5afEvaliKd2+ASdciwW9/brXdGyr/dkg5nJZNsw08XlddQOu3cMg/dahGs2av0iE5F5gIwBhzJnkW1lQULS0QRM5qkg2xryWjIV3TOYijSxv5YzcT9G26dEj5M="
  on:
    branch: release

notifications:
  slack:
    rooms:
    - secure: "c3I1MHa8NE+Snh4PrWpN+fFVdS5tMGqVY8L+O4J2Xmaz+MExEXz+QyjqlSnMiQG3Gq6nVa4XJQR7wGvd7JiYP/uXMqImh1Lh9cEGfIbVcpn6XkWa8Pqdh88D82Uwlfw3lipd+C2zMznQ7nkFtB8E4pznj9BjwUjik9RsCs8tv8uvHllCpvagICURjRp4rR2VGBynkHBi8/rMtw7zJU4BGIcaBFhUa5mL6D4y0CerZVW/ggOVaquzzfO0DrBIOAHo2fNXmH6cmsuUjlT1rNEMa3pf+txpTtWoDO4ipocO81sHgY0CBGIuRyYV1/+V6E5Cq5kq7TQXryrH9vDMelhMxi/zJf0HLEv6Qf6dTFuplDNL7ACCN5MtRkcnZUqq7FPHcsjZdmpyfbaTNMAK8/GfcbU6vvlIdIOAx0+fp64IbkdYfyPIcBeS6symA4f1NxfQY0odNTdrHeW/ZY1zwsUEkGpB71keefcIp/CXUWPmrZjwfZVGAKdXLPfVzOhRssR49qxBFZT3Wdem8isS2dvHC3bXVAU62M38mQiaLs63pMia163sUKKvcOqgzcLHuPaE4albP/1EDHsin7Jvem1bFRJhavnyb32aNE/DKvwGgLJodI0lxhrY2cfS/gz+EDdYyknf5UjfaWJkKRpWRpKSOGkZGA3Bt4sinNneLmk3XTI="
